var _ = require("lodash");

const V1 = {
    version: "1",
    protocol: "https",
    hostname: "42matters.com",
    pathname: "api",
    dateformat: "dd-mm-YYYY",
    limitRange: _.range(1, 101)
};

const GooglePlayStoreAPI = {
    endpoints: {
        lookup: "apps/lookup.json",
        search: "apps/search.json",
        query: "apps/query.json",
        availability: "apps/availability.json",
        charts: "apps/top_google_charts.json"
    },
    charts: {
        "topselling_free": "Top Selling Free",
        "topselling_paid": "Top Selling Paid",
        "topgrossing": "Top Grossing Apps",
        "topselling_new_free": "Top New Free (Only Apps and Games)",
        "topselling_new_paid": "Top New Paid (Only Apps and Games)"
    },
    countries: {
        "US": "United States",
        "AR": "Argentina",
        "AU": "Australia",
        "AT": "Austria",
        "BE": "Belgium",
        "BR": "Brazil",
        "BG": "Bulgaria",
        "CA": "Canada",
        "CL": "Chile",
        "CN": "China",
        "CO": "Colombia",
        "HR": "Croatia",
        "CZ": "Czech Republic",
        "DK": "Denmark",
        "EG": "Egypt",
        "EE": "Estonia",
        "FI": "Finland",
        "FR": "France",
        "DE": "Germany",
        "GR": "Greece",
        "HK": "Hong Kong",
        "HU": "Hungary",
        "IN": "India",
        "ID": "Indonesia",
        "IL": "Israel",
        "IT": "Italy",
        "JP": "Japan",
        "LV": "Latvia",
        "LT": "Lithuania",
        "MY": "Malaysia",
        "MX": "Mexico",
        "NL": "Netherlands",
        "NZ": "New Zealand",
        "NO": "Norway",
        "PE": "Peru",
        "PH": "Phillipines",
        "PL": "Poland",
        "PT": "Portugal",
        "RO": "Romania",
        "RU": "Russian Federation",
        "SA": "Saudi Arabia",
        "RS": "Serbia",
        "SG": "Singapore",
        "SK": "Slovakia",
        "ZA": "South Africa",
        "KR": "South Korea",
        "ES": "Spain",
        "SE": "Sweden",
        "CH": "Switzerland",
        "TW": "Taiwan",
        "TH": "Thailand",
        "TR": "Turkey",
        "UA": "Ukraine",
        "AE": "United Arab Emirates",
        "GB": "United Kingdom",
        "VN": "Vietnam"
    },
    languages: {
        "en": "English",
        "bg": "Bulgarian",
        "ca": "Catalan",
        "cs": "Czech",
        "da": "Danish",
        "de": "German",
        "el": "Greek",
        "es": "Spanish",
        "fi": "Finnish",
        "fr": "French",
        "hi": "Hindi",
        "hr": "Croatian",
        "hu": "Hungarian",
        "id": "Indonesian",
        "it": "Italian",
        "ja": "Japanese",
        "ko": "Korean",
        "ms": "Malay",
        "nl": "Dutch",
        "no": "Norwegian",
        "pl": "Polish",
        "pt": "Portuguese",
        "pt-br": "Portuguese-Brazilian",
        "ro": "Romanian",
        "ru": "Russian",
        "sk": "Slovak",
        "sr": "Serbian",
        "sv": "Swedish",
        "th": "Thai",
        "tr": "Turkish",
        "uk": "Ukrainian",
        "vi": "Vietnamese",
        "zh-cn": "Chinese Simplified",
        "zh-tw": "Chinese Traditional"
    },
    categories: {
        "APPS": "All",
        "GAMES": "All games",
        "BOOKS_AND_REFERENCE": "Books & Reference",
        "BUSINESS": "Business",
        "COMICS": "Comics",
        "COMMUNICATION": "Communication",
        "EDUCATION": "Education",
        "ENTERTAINMENT": "Entertainment",
        "FINANCE": "Finance",
        "HEALTH_AND_FITNESS": "Health & Fitness",
        "LIFESTYLE": "Lifestyle",
        "MEDIA_AND_VIDEO": "Media & Video",
        "MEDICAL": "Medical",
        "MUSIC_AND_AUDIO": "Music & Audio",
        "NEWS_AND_MAGAZINES": "News & Magazines",
        "PERSONALIZATION": "Personalization",
        "PHOTOGRAPHY": "Photography",
        "PRODUCTIVITY": "Productivity",
        "SHOPPING": "Shopping",
        "SOCIAL": "Social",
        "SPORTS": "Sports",
        "TOOLS": "Tools",
        "TRANSPORTATION": "Transportation",
        "TRAVEL_AND_LOCAL": "Travel & Local",
        "WEATHER": "Weather",
        "LIBRARIES_AND_DEMO": "Libraries & Demo",
        "GAME_ARCADE": "Arcade",
        "GAME_PUZZLE": "Puzzle",
        "GAME_CARD": "Cards",
        "GAME_CASUAL": "Casual",
        "GAME_RACING": "Racing",
        "GAME_SPORTS": "Sport Games",
        "GAME_ACTION": "Action",
        "GAME_ADVENTURE": "Adventure",
        "GAME_BOARD": "Board",
        "GAME_CASINO": "Casino",
        "GAME_EDUCATIONAL": "Educational",
        "GAME_FAMILY": "Family",
        "GAME_MUSIC	Music": "Games",
        "GAME_ROLE_PLAYING": "Role Playing",
        "GAME_SIMULATION": "Simulation",
        "GAME_STRATEGY": "Strategy",
        "GAME_TRIVIA": "Trivia",
        "GAME_WORD": "Word Games",
        "APP_WALLPAPER": "App Wallpaper",
        "APP_WIDGETS": "App Widgets",
        "ANDROID_WEAR": "Android Wear",
        "FAMILY": "Family All Ages",
        "FAMILY_UNDER_5": "Family Ages 5 & Under",
        "FAMILY_6_TO_8": "Family Ages 6-8",
        "FAMILY_9_AND_UP": "Family Ages 9 & Up",
        "FAMILY_ACTION": "Family Action",
        "FAMILY_BRAINGAMES": "Family Brain Games",
        "FAMILY_CREATE": "Family Create",
        "FAMILY_EDUCATION": "Family Education",
        "FAMILY_MUSICVIDEO": "Family Music & Video",
        "FAMILY_PRETEND": "Family Pretend Play"
    }
};


module.exports = {
    V1: V1,
    GooglePlayStoreAPI: GooglePlayStoreAPI
};